/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ErrorResponse {
  error: string;
}

export interface MessageResponse {
  message: string;
}

export interface RegisterRequest {
  /**
   * @minLength 3
   * @maxLength 30
   */
  username: string;
  /** @minLength 6 */
  password: string;
  email?: string | null;
  referralCode?: string | null;
}

export interface LoginRequest {
  username: string;
  password: string;
}

export interface User {
  id: number;
  username: string;
  email?: string | null;
  balance: number;
  isAdmin: boolean;
  referralCode?: string | null;
  avatarUrl?: string | null;
  createdAt: string;
}

export interface AuthResponse {
  user: User;
  message: string;
}

export interface UserStats {
  totalProfit: number;
  biggestWin: number;
  biggestBet: number;
  gamesPlayed: number;
  winStreak: number;
  currentStreak: number;
  totalWins: number;
  totalLosses: number;
  lastDailyClaim?: string | null;
  balance: number;
}

export interface DailyRewardResponse {
  reward: number;
  newBalance: number;
  message: string;
}

export interface RecentBet {
  username: string;
  betAmount: number;
  gameType: string;
  result: string;
  payout: number;
  timestamp: string;
}

export interface PoolInfo {
  forceReloadAt?: number;
  disabledGames?: string[];
  totalAmount: number;
  biggestWin: number;
  biggestBet: number;
  maxBet: number;
  recentBigBets: RecentBet[];
}

export type RouletteRequestColor =
  (typeof RouletteRequestColor)[keyof typeof RouletteRequestColor];

export const RouletteRequestColor = {
  red: "red",
  black: "black",
} as const;

export interface RouletteRequest {
  betAmount: number;
  color: RouletteRequestColor;
}

export interface RouletteResult {
  won: boolean;
  resultColor: string;
  resultNumber: number;
  betAmount: number;
  payout: number;
  newBalance: number;
  winChance: number;
}

export type PlinkoRequestRisk =
  (typeof PlinkoRequestRisk)[keyof typeof PlinkoRequestRisk];

export const PlinkoRequestRisk = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;

export interface PlinkoRequest {
  betAmount: number;
  risk: PlinkoRequestRisk;
}

export type PlinkoResultPathItem = {
  x: number;
  y: number;
};

export interface PlinkoResult {
  won: boolean;
  multiplier: number;
  path: PlinkoResultPathItem[];
  betAmount: number;
  payout: number;
  newBalance: number;
  slot: number;
  winChance: number;
}

export interface Transaction {
  id: number;
  gameType: string;
  betAmount: number;
  result: string;
  payout: number;
  multiplier?: number | null;
  timestamp: string;
}

export interface TransactionList {
  transactions: Transaction[];
  total: number;
}

export interface LeaderboardEntry {
  rank: number;
  username: string;
  value: number;
  label: string;
}

export interface LeaderboardList {
  entries: LeaderboardEntry[];
}

export interface RecentWin {
  username: string;
  payout: number;
  betAmount: number;
  gameType: string;
  multiplier?: number | null;
  timestamp: string;
}

export interface RecentWinsList {
  wins: RecentWin[];
}

export interface AdminRefillPoolRequest {
  amount: number;
}

export interface AdminRefillPoolResponse {
  message: string;
  newPoolAmount: number;
}

export interface AdminRefillPlayerRequest {
  userId: number;
  amount: number;
}

export interface AdminRefillPlayerResponse {
  message: string;
  newBalance: number;
}

export interface TransferRequest {
  toUsername: string;
  amount: number;
}

export interface TransferResponse {
  message: string;
  newBalance: number;
}

export interface AdminSeizeRequest {
  fromUserId: number;
  amount: number;
  destination: "pool" | "user";
  toUserId?: number;
}

export interface AdminSeizeResponse {
  message: string;
  amountSeized: number;
  newVictimBalance: number;
}

export interface AdminResetAllBalancesRequest {
  newBalance?: number;
}

export interface AdminResetAllBalancesResponse {
  message: string;
  usersReset: number;
}

export interface AdminPlayer {
  id: number;
  username: string;
  balance: number;
  isAdmin: boolean;
  gamesPlayed: number;
  totalWins: number;
  totalLosses: number;
}

export interface AdminPlayerList {
  players: AdminPlayer[];
}

export interface ChangeUsernameRequest {
  /**
   * @minLength 3
   * @maxLength 30
   */
  newUsername: string;
}

export interface ChangeAvatarRequest {
  avatarUrl: string;
}

export interface ChangeProfileResponse {
  message: string;
  newBalance: number;
  cost: number;
}

export interface ProfileChangeCosts {
  usernameChangeCost: number;
  avatarChangeCost: number;
}

export interface AdminSettingsResponse {
  usernameChangeCost: number;
  avatarChangeCost: number;
  disabledGames?: string[];
}

export interface AdminUpdateSettingsRequest {
  usernameChangeCost?: number | null;
  avatarChangeCost?: number | null;
  disabledGames?: string[] | null;
}

export type GetTransactionsParams = {
  game?: string;
  limit?: number;
  offset?: number;
};
