/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

/**
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  status: zod.string(),
});

/**
 * @summary Register a new user
 */
export const registerBodyUsernameMin = 3;
export const registerBodyUsernameMax = 30;

export const registerBodyPasswordMin = 6;

export const RegisterBody = zod.object({
  username: zod
    .string()
    .min(registerBodyUsernameMin)
    .max(registerBodyUsernameMax),
  password: zod.string().min(registerBodyPasswordMin),
  email: zod.string().nullish(),
  referralCode: zod.string().nullish(),
});

export const RegisterResponse = zod.object({
  user: zod.object({
    id: zod.number(),
    username: zod.string(),
    email: zod.string().nullish(),
    balance: zod.number(),
    isAdmin: zod.boolean(),
    referralCode: zod.string().nullish(),
    avatarUrl: zod.string().nullish(),
    createdAt: zod.string(),
  }),
  message: zod.string(),
});

/**
 * @summary Login
 */
export const LoginBody = zod.object({
  username: zod.string(),
  password: zod.string(),
});

export const LoginResponse = zod.object({
  user: zod.object({
    id: zod.number(),
    username: zod.string(),
    email: zod.string().nullish(),
    balance: zod.number(),
    isAdmin: zod.boolean(),
    referralCode: zod.string().nullish(),
    avatarUrl: zod.string().nullish(),
    createdAt: zod.string(),
  }),
  message: zod.string(),
});

/**
 * @summary Logout
 */
export const LogoutResponse = zod.object({
  message: zod.string(),
});

/**
 * @summary Get current user
 */
export const GetMeResponse = zod.object({
  id: zod.number(),
  username: zod.string(),
  email: zod.string().nullish(),
  balance: zod.number(),
  isAdmin: zod.boolean(),
  isOwner: zod.boolean().optional(),
  isGuest: zod.boolean().optional(),
  isCrazyGamesLinked: zod.boolean().optional(),
  referralCode: zod.string().nullish(),
  avatarUrl: zod.string().nullish(),
  createdAt: zod.string(),
  suspendedUntil: zod.string().nullish(),
  bannedUntil: zod.string().nullish(),
  permanentlyBanned: zod.boolean().optional(),
  banReason: zod.string().nullish(),
});

/**
 * @summary Get current user stats
 */
export const GetUserStatsResponse = zod.object({
  totalProfit: zod.number(),
  biggestWin: zod.number(),
  biggestBet: zod.number(),
  gamesPlayed: zod.number(),
  winStreak: zod.number(),
  currentStreak: zod.number(),
  totalWins: zod.number(),
  totalLosses: zod.number(),
  lastDailyClaim: zod.string().nullish(),
  balance: zod.number(),
});

/**
 * @summary Claim daily reward
 */
export const ClaimDailyRewardResponse = zod.object({
  reward: zod.number(),
  newBalance: zod.number(),
  message: zod.string(),
});

/**
 * @summary Get global pool info
 */
export const GetPoolResponse = zod.object({
  totalAmount: zod.number(),
  biggestWin: zod.number(),
  biggestBet: zod.number(),
  maxBet: zod.number(),
  forceReloadAt: zod.number().optional(),
  disabledGames: zod.array(zod.string()).optional(),
  recentBigBets: zod.array(
    zod.object({
      username: zod.string(),
      betAmount: zod.number(),
      gameType: zod.string(),
      result: zod.string(),
      payout: zod.number(),
      timestamp: zod.string(),
    }),
  ),
});

/**
 * @summary Play roulette
 */
export const PlayRouletteBody = zod.object({
  betAmount: zod.number(),
  color: zod.enum(["red", "black", "green"]),
});

export const PlayRouletteResponse = zod.object({
  won: zod.boolean(),
  resultColor: zod.string(),
  resultNumber: zod.number(),
  betAmount: zod.number(),
  payout: zod.number(),
  newBalance: zod.number(),
  winChance: zod.number(),
});

/**
 * @summary Play plinko
 */
export const PlayPlinkoBody = zod.object({
  betAmount: zod.number(),
  risk: zod.enum(["low", "medium", "high"]),
});

export const PlayPlinkoResponse = zod.object({
  won: zod.boolean(),
  multiplier: zod.number(),
  path: zod.array(
    zod.object({
      x: zod.number(),
      y: zod.number(),
    }),
  ),
  betAmount: zod.number(),
  payout: zod.number(),
  newBalance: zod.number(),
  slot: zod.number(),
  winChance: zod.number(),
});

/**
 * @summary Get transaction history
 */
export const GetTransactionsQueryParams = zod.object({
  game: zod.coerce.string().optional(),
  limit: zod.coerce.number().optional(),
  offset: zod.coerce.number().optional(),
});

export const GetTransactionsResponse = zod.object({
  transactions: zod.array(
    zod.object({
      id: zod.number(),
      gameType: zod.string(),
      betAmount: zod.number(),
      result: zod.string(),
      payout: zod.number(),
      multiplier: zod.number().nullish(),
      timestamp: zod.string(),
    }),
  ),
  total: zod.number(),
});

/**
 * @summary Get richest players leaderboard
 */
export const GetRichestPlayersResponse = zod.object({
  entries: zod.array(
    zod.object({
      rank: zod.number(),
      username: zod.string(),
      value: zod.number(),
      label: zod.string(),
    }),
  ),
});

/**
 * @summary Get biggest winners leaderboard
 */
export const GetBiggestWinnersResponse = zod.object({
  entries: zod.array(
    zod.object({
      rank: zod.number(),
      username: zod.string(),
      value: zod.number(),
      label: zod.string(),
    }),
  ),
});

/**
 * @summary Get biggest bettors leaderboard
 */
export const GetBiggestBettorsResponse = zod.object({
  entries: zod.array(
    zod.object({
      rank: zod.number(),
      username: zod.string(),
      value: zod.number(),
      label: zod.string(),
    }),
  ),
});

/**
 * @summary Get recent big wins
 */
export const GetRecentBigWinsResponse = zod.object({
  wins: zod.array(
    zod.object({
      username: zod.string(),
      payout: zod.number(),
      betAmount: zod.number(),
      gameType: zod.string(),
      multiplier: zod.number().nullish(),
      timestamp: zod.string(),
    }),
  ),
});

/**
 * @summary Refill the global pool (admin only)
 */
export const AdminRefillPoolBody = zod.object({
  amount: zod.number(),
});

export const AdminRefillPoolResponse = zod.object({
  message: zod.string(),
  newPoolAmount: zod.number(),
});

/**
 * @summary Refill a player's balance (admin only)
 */
export const AdminRefillPlayerBody = zod.object({
  userId: zod.number(),
  amount: zod.number(),
});

export const AdminRefillPlayerResponse = zod.object({
  message: zod.string(),
  newBalance: zod.number(),
});

/**
 * @summary Reset all players' balances to a default amount (admin only)
 */
export const TransferBody = zod.object({
  toUsername: zod.string().min(1),
  amount: zod.number().positive(),
});

export const TransferResponse = zod.object({
  message: zod.string(),
  newBalance: zod.number(),
});

export const AdminSeizeBody = zod.object({
  fromUserId: zod.number().int(),
  amount: zod.number().positive(),
  destination: zod.enum(["pool", "user"]),
  toUserId: zod.number().int().optional(),
});

export const AdminSeizeResponse = zod.object({
  message: zod.string(),
  amountSeized: zod.number(),
  newVictimBalance: zod.number(),
});

export const AdminResetAllBalancesBody = zod.object({
  newBalance: zod.number().optional(),
});

export const AdminResetAllBalancesResponse = zod.object({
  message: zod.string(),
  usersReset: zod.number(),
});

/**
 * @summary Change username (costs coins)
 */
export const changeUsernameBodyNewUsernameMin = 3;
export const changeUsernameBodyNewUsernameMax = 30;

export const ChangeUsernameBody = zod.object({
  newUsername: zod
    .string()
    .min(changeUsernameBodyNewUsernameMin)
    .max(changeUsernameBodyNewUsernameMax),
});

export const ChangeUsernameResponse = zod.object({
  message: zod.string(),
  newBalance: zod.number(),
  cost: zod.number(),
});

/**
 * @summary Change avatar URL (costs coins)
 */
export const ChangeAvatarBody = zod.object({
  avatarUrl: zod.string(),
});

export const ChangeAvatarResponse = zod.object({
  message: zod.string(),
  newBalance: zod.number(),
  cost: zod.number(),
});

/**
 * @summary Get costs for profile changes
 */
export const GetProfileChangeCostsResponse = zod.object({
  usernameChangeCost: zod.number(),
  avatarChangeCost: zod.number(),
});

/**
 * @summary Get all admin settings
 */
export const AdminGetSettingsResponse = zod.object({
  usernameChangeCost: zod.number(),
  avatarChangeCost: zod.number(),
  disabledGames: zod.array(zod.string()).optional(),
});

/**
 * @summary Update admin settings
 */
export const AdminUpdateSettingsBody = zod.object({
  usernameChangeCost: zod.number().nullish(),
  avatarChangeCost: zod.number().nullish(),
  disabledGames: zod.array(zod.string()).nullish(),
});

export const AdminUpdateSettingsResponse = zod.object({
  usernameChangeCost: zod.number(),
  avatarChangeCost: zod.number(),
  disabledGames: zod.array(zod.string()).optional(),
});

/**
 * @summary List all players (admin only)
 */
export const AdminListPlayersResponse = zod.object({
  players: zod.array(
    zod.object({
      id: zod.number(),
      username: zod.string(),
      balance: zod.number(),
      isAdmin: zod.boolean(),
      gamesPlayed: zod.number(),
      totalWins: zod.number(),
      totalLosses: zod.number(),
    }),
  ),
});
