[[pages]]
path = "/"
screenshotTimestamp = "2026-04-01T15:13:02Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/d5e723d6-63a2-48d8-99ed-fd6523247667/db1fcd2e-708d-45be-b0b7-bf1a9597dcef/kTprqeX"

[[pages]]
path = "/games"
screenshotTimestamp = "2026-04-01T02:12:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/d5e723d6-63a2-48d8-99ed-fd6523247667/db1fcd2e-708d-45be-b0b7-bf1a9597dcef/HlDvBID"

[[pages]]
path = "/register"
screenshotTimestamp = "2026-03-26T20:25:09Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/YJ3R3SG"

[[pages]]
path = "/games/roulette"
screenshotTimestamp = "2026-03-26T15:23:40Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/eyUAS0G"

[[pages]]
path = "/profile"
screenshotTimestamp = "2026-03-26T18:27:15Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/TdUPCsa"

[[pages]]
path = "/plinko"
screenshotTimestamp = "2026-03-25T13:35:05Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/XzeaG6f"

[[pages]]
path = "/games/plinko"
screenshotTimestamp = "2026-03-26T21:36:16Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/UhQCQ0X"

[[pages]]
path = "/games/blackjack"
screenshotTimestamp = "2026-03-25T17:51:42Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/WHx4dza"

[[pages]]
path = "/games/crash"
screenshotTimestamp = "2026-03-25T18:31:08Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/whi27ke"

[[pages]]
path = "/games/mines"
screenshotTimestamp = "2026-03-26T20:24:50Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/pHab3jM"

[[pages]]
path = "/games/dice"
screenshotTimestamp = "2026-03-25T17:51:54Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/yX1JTxO"

[[pages]]
path = "/games/wheel"
screenshotTimestamp = "2026-03-25T17:37:06Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/YtuigzD"

[[pages]]
path = "/games/slots"
screenshotTimestamp = "2026-03-25T17:51:27Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/YFz6y6q"

[[pages]]
path = "/games/coinflip"
screenshotTimestamp = "2026-03-25T17:51:30Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/YFmy93s"

[[pages]]
path = "/games/guess"
screenshotTimestamp = "2026-03-25T17:52:05Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/j7wULS3"

[[pages]]
path = "/login"
screenshotTimestamp = "2026-03-31T14:22:35Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/d5e723d6-63a2-48d8-99ed-fd6523247667/db1fcd2e-708d-45be-b0b7-bf1a9597dcef/VBqLJsZ"

[[pages]]
path = "/roulette"
screenshotTimestamp = "2026-03-27T16:54:35Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/hHpWRkA"

[[pages]]
path = "/admin"
screenshotTimestamp = "2026-03-26T21:18:36Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/LEit846"

[[pages]]
path = "/chat"
screenshotTimestamp = "2026-03-27T13:55:16Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/7XqQJX6"

[[pages]]
path = "/notifications"
screenshotTimestamp = "2026-03-26T21:36:11Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/3sNtHA0"

[[pages]]
path = "/leaderboard"
screenshotTimestamp = "2026-03-31T21:26:28Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/d5e723d6-63a2-48d8-99ed-fd6523247667/db1fcd2e-708d-45be-b0b7-bf1a9597dcef/nW5Js6C"

[[pages]]
path = "/games/war"
screenshotTimestamp = "2026-03-27T16:32:10Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/URpu2kB"

[[pages]]
path = "/multiplayer"
screenshotTimestamp = "2026-04-01T02:13:10Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/d5e723d6-63a2-48d8-99ed-fd6523247667/db1fcd2e-708d-45be-b0b7-bf1a9597dcef/oAIuyJQ"

[[pages]]
path = "/games/highlow"
screenshotTimestamp = "2026-03-27T16:43:25Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/TFcKwCR"

[[pages]]
path = "/pool-casino/pyramid"
screenshotTimestamp = "2026-03-27T17:33:08Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/8aNfGhv"

[[pages]]
path = "/games/pyramid"
screenshotTimestamp = "2026-03-27T17:33:21Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/7CmXDLj"

[[pages]]
path = "/games/icebreak"
screenshotTimestamp = "2026-03-27T17:33:23Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/C4RUbbe"

[[pages]]
path = "/games/advwheel"
screenshotTimestamp = "2026-03-27T17:33:33Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/b880271f-6686-4c58-918f-732bf4a51358/bd91b846-5ca3-4150-a3bd-4ac01861fb0e/7NEraK6"

[[pages]]
path = "/badges"
screenshotTimestamp = "2026-03-31T14:12:47Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/d5e723d6-63a2-48d8-99ed-fd6523247667/db1fcd2e-708d-45be-b0b7-bf1a9597dcef/v7R3sQP"

[[pages]]
path = "/casinos"
screenshotTimestamp = "2026-04-01T02:19:23Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/d5e723d6-63a2-48d8-99ed-fd6523247667/db1fcd2e-708d-45be-b0b7-bf1a9597dcef/1uoVA2P"

[[pages]]
path = "/casinos/1"
screenshotTimestamp = "2026-04-01T02:19:45Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/d5e723d6-63a2-48d8-99ed-fd6523247667/db1fcd2e-708d-45be-b0b7-bf1a9597dcef/sk3o128"

[[pages]]
path = "/casino/1"
screenshotTimestamp = "2026-04-01T02:20:05Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/d5e723d6-63a2-48d8-99ed-fd6523247667/db1fcd2e-708d-45be-b0b7-bf1a9597dcef/dnXKGn5"
