/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PlinkoResultPathItem } from "./plinkoResultPathItem";

export interface PlinkoResult {
  won: boolean;
  multiplier: number;
  path: PlinkoResultPathItem[];
  betAmount: number;
  payout: number;
  newBalance: number;
  slot: number;
  winChance: number;
}
