/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */

export type PlinkoRequestRisk =
  (typeof PlinkoRequestRisk)[keyof typeof PlinkoRequestRisk];

export const PlinkoRequestRisk = {
  low: "low",
  medium: "medium",
  high: "high",
} as const;
