/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PlinkoRequestRisk } from "./plinkoRequestRisk";

export interface PlinkoRequest {
  betAmount: number;
  risk: PlinkoRequestRisk;
}
