/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */
import type { RecentBet } from "./recentBet";

export interface PoolInfo {
  totalAmount: number;
  biggestWin: number;
  biggestBet: number;
  maxBet: number;
  recentBigBets: RecentBet[];
}
