/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */
import type { RouletteRequestColor } from "./rouletteRequestColor";

export interface RouletteRequest {
  betAmount: number;
  color: RouletteRequestColor;
}
