/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */

export interface RouletteResult {
  won: boolean;
  resultColor: string;
  resultNumber: number;
  betAmount: number;
  payout: number;
  newBalance: number;
  winChance: number;
}
