/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */

export type RouletteRequestColor =
  (typeof RouletteRequestColor)[keyof typeof RouletteRequestColor];

export const RouletteRequestColor = {
  red: "red",
  black: "black",
} as const;
