/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */

export interface User {
  id: number;
  username: string;
  email?: string | null;
  balance: number;
  isAdmin: boolean;
  referralCode?: string | null;
  avatarUrl?: string | null;
  createdAt: string;
}
