/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * PoolCasino API specification
 * OpenAPI spec version: 0.1.0
 */

export interface UserStats {
  totalProfit: number;
  biggestWin: number;
  biggestBet: number;
  gamesPlayed: number;
  winStreak: number;
  currentStreak: number;
  totalWins: number;
  totalLosses: number;
  lastDailyClaim?: string | null;
  balance: number;
}
